#!/bin/bash
#
# bootstrap - dependency management
#

set -e

cd "$(dirname "$0")/.."

# Get environment variables, if they exist.
ENV_FILE=${ENV_FILE:-../env.sh}
if [ -f "$ENV_FILE" ]; then
  echo "==> Loading environment from ${ENV_FILE}"
  source $ENV_FILE
fi

## Set-up virtualenv
# Check we've got virtualenv available.
command -v virtualenv >/dev/null 2>&1 || {
  echo "==> The virtualenv package is required, aborting.";
  exit 1;
}

echo "==> Setting up the virtualenv..."
# Some env variables used during development seem to make things break - set
# them back to the defaults which is what they would have on the servers.
PYTHONDONTWRITEBYTECODE=""

# This allows us to override the location of the virtualenv
VIRTUALENV_DIR=${VIRTUALENV_DIR:-venv}
virtualenv_activate="$VIRTUALENV_DIR/bin/activate"
if [ ! -f "$virtualenv_activate" ]; then
  virtualenv $VIRTUALENV_DIR
fi
source $virtualenv_activate

# Upgrade python package management
curl -L -s https://raw.github.com/mysociety/commonlib/master/bin/get_pip.bash | bash

# Install what we need
pip install -r requirements.txt

echo "==> Done setting up virtualenv."

## Check for Terraform. We'll only warn here unless running a build.
if ! command -v terraform >/dev/null 2>&1 ; then
  if [ -n "$BUILD" ]; then
    echo "==> Terraform not found, build aborting."
    exit 2
  else
    echo "==> Warning: Terraform not found, required for build."
  fi
else
  echo "==> Terraform found, OK."
fi

## Git submodules, only needed for build.
if [ -n "$BUILD" ]; then
  echo "==> Checking git submodules..."
  git submodule update --init
fi

## Docker image pull, don't bother if building as we'll separate checks there.
if [ -z "$BUILD" ]; then
  echo "==> Checking for local copy of required docker images..."
  docker-compose pull
fi
