#!/bin/bash
#
# update - update project
#

function build_conf {
  template=$1
  file=$2
  /usr/bin/env python -c 'import os
import sys
import jinja2
sys.stdout.write(
    jinja2.Template(sys.stdin.read()
).render(env=os.environ))' <$template >$file
}

set -e

cd "$(dirname "$0")/.."

script/bootstrap

# Get environment variables, if they exist.
ENV_FILE=${ENV_FILE:-conf/env.sh}
if [ -f "$ENV_FILE" ]; then
  echo "==> Loading environment from ${ENV_FILE}"
  source $ENV_FILE
fi

echo "==> Activating virtualenv..."
VIRTUALENV_DIR=${VIRTUALENV_DIR:-venv}
source ${VIRTUALENV_DIR}/bin/activate

echo "==> Building configuration..."
umask 027
for template_file in conf/*.j2 ; do
  [ -e "${template_file%%.j2}" ] && cp ${template_file%%.j2} ${template_file%%.j2}.last
  build_conf $template_file ${template_file%%.j2}
  cp ${template_file%%.j2} ${template_file%%.j2}.deployed
done
